include:
  - project: kirigami2/cloud/ops/cicd
    file: /templates/.ci_kit.yml
    ref: dev

deploy-package:dev:
  image: node:latest
  stage: deploy
  when: manual
  only:
    - dev
  variables:
    npm_config_registry: $CI_API_V4_URL/projects/${CI_PROJECT_ID}/packages/npm/
    NPM_TOKEN: $CI_JOB_TOKEN
  before_script:
    - echo "@kirigami-pencil:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - echo $(node -p "require('./package.json').version") >> VERSION_R
    - echo "Deploying version $VERSION_NUMBER to GitLab Package Registry"
  script:
     - npm publish
  artifacts:
    paths:
      - VERSION_NUMBER
  extends: 
    - .only_in_mr_to_dev
     
# ------------------------------------------------------------------------
# Run_apps_pipeline
# -----------------------------------------------------------------------
# run_apps_pipeline:
#   stage: apps_pipeline
#   inherit:
#     variables: false
#   trigger:
#     strategy: depend
#     include:
#       - artifact: out.yml
#         job: build_ci
#   extends: 
#     - .only_in_mr_to_dev


# -----------------------------------------------------------------------
# Ordered stages
# ------------------------------------------------------------------------
stages:
  - lint
  - plan
  - deploy
  - tag
  - release
  - post-deploy
